// ==============================================================================
// PAIMANA PREDICT — PROJECT RISK & ACTION WORKFLOW STATE MACHINES
// ==============================================================================

export const PROJECT_RISK_STATES = {
  ON_TRACK: 'ON_TRACK',
  WATCH: 'WATCH',
  AT_RISK: 'AT_RISK',
  HIGH_RISK: 'HIGH_RISK',
  CRITICAL: 'CRITICAL',
  INTERVENTION: 'INTERVENTION',
  RECOVERY: 'RECOVERY',
};

export const ACTION_STATES = {
  RISK_DETECTED: 'RISK_DETECTED',
  RECOMMENDED: 'RECOMMENDED',
  ACTION_ASSIGNED: 'ACTION_ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  OFFICER_REVIEW: 'OFFICER_REVIEW',
  RESOLVED: 'RESOLVED',
  RECALCULATED: 'RECALCULATED',
};

// Valid transitions for Project Risk Lifecycle
export const RISK_STATE_TRANSITIONS = {
  [PROJECT_RISK_STATES.ON_TRACK]: [PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.AT_RISK],
  [PROJECT_RISK_STATES.WATCH]: [PROJECT_RISK_STATES.ON_TRACK, PROJECT_RISK_STATES.AT_RISK, PROJECT_RISK_STATES.HIGH_RISK],
  [PROJECT_RISK_STATES.AT_RISK]: [PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.HIGH_RISK, PROJECT_RISK_STATES.CRITICAL],
  [PROJECT_RISK_STATES.HIGH_RISK]: [PROJECT_RISK_STATES.CRITICAL, PROJECT_RISK_STATES.INTERVENTION, PROJECT_RISK_STATES.RECOVERY],
  [PROJECT_RISK_STATES.CRITICAL]: [PROJECT_RISK_STATES.INTERVENTION, PROJECT_RISK_STATES.HIGH_RISK],
  [PROJECT_RISK_STATES.INTERVENTION]: [PROJECT_RISK_STATES.RECOVERY, PROJECT_RISK_STATES.CRITICAL],
  [PROJECT_RISK_STATES.RECOVERY]: [PROJECT_RISK_STATES.ON_TRACK, PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.AT_RISK],
};

// Valid transitions for Action Workflow Lifecycle
export const ACTION_STATE_TRANSITIONS = {
  [ACTION_STATES.RISK_DETECTED]: [ACTION_STATES.RECOMMENDED, ACTION_STATES.ACTION_ASSIGNED],
  [ACTION_STATES.RECOMMENDED]: [ACTION_STATES.ACTION_ASSIGNED, ACTION_STATES.RESOLVED],
  [ACTION_STATES.ACTION_ASSIGNED]: [ACTION_STATES.IN_PROGRESS, ACTION_STATES.RECOMMENDED],
  [ACTION_STATES.IN_PROGRESS]: [ACTION_STATES.EVIDENCE_SUBMITTED, ACTION_STATES.OFFICER_REVIEW, ACTION_STATES.RESOLVED],
  [ACTION_STATES.EVIDENCE_SUBMITTED]: [ACTION_STATES.OFFICER_REVIEW, ACTION_STATES.RESOLVED, ACTION_STATES.IN_PROGRESS],
  [ACTION_STATES.OFFICER_REVIEW]: [ACTION_STATES.RESOLVED, ACTION_STATES.IN_PROGRESS],
  [ACTION_STATES.RESOLVED]: [ACTION_STATES.RECALCULATED],
  [ACTION_STATES.RECALCULATED]: [ACTION_STATES.ACTION_ASSIGNED, ACTION_STATES.RESOLVED],
};

/**
 * Computes the recommended risk state from numerical telemetry
 */
export const evaluateProjectRiskState = (project) => {
  const costGrowth = Number(project.cost_growth_pct || 0);
  const extensionMonths = Number(project.schedule_extension_months || 0);
  const progress = Number(project.physical_progress || 0);

  if (costGrowth > 100 || extensionMonths > 36) {
    return PROJECT_RISK_STATES.CRITICAL;
  }
  if (costGrowth > 40 || extensionMonths > 18) {
    return PROJECT_RISK_STATES.HIGH_RISK;
  }
  if (costGrowth > 15 || extensionMonths > 6) {
    return PROJECT_RISK_STATES.AT_RISK;
  }
  if (costGrowth > 0 || progress < 50) {
    return PROJECT_RISK_STATES.WATCH;
  }
  return PROJECT_RISK_STATES.ON_TRACK;
};
