// ==============================================================================
// PAIMANA PREDICT — PROJECT RISK & ACTION WORKFLOW STATE MACHINES
// ==============================================================================

export const PROJECT_RISK_STATES = {
  ON_TRACK: 'ON_TRACK',
  WATCH: 'WATCH',
  AT_RISK: 'AT_RISK',
  HIGH_RISK: 'HIGH_RISK',
  CRITICAL: 'CRITICAL',
  INTERVENTION: 'INTERVENTION',
  RECOVERY: 'RECOVERY',
};

export const ACTION_STATES = {
  RISK_DETECTED: 'RISK_DETECTED',
  RECOMMENDED: 'RECOMMENDED',
  ACTION_ASSIGNED: 'ACTION_ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  OFFICER_REVIEW: 'OFFICER_REVIEW',
  RESOLVED: 'RESOLVED',
  RECALCULATED: 'RECALCULATED',
};

// ==============================================================================
// 14-STATE OFFICIAL GOVERNMENT PROJECT OPERATIONAL LIFECYCLE
// ==============================================================================
export const PROJECT_OPERATIONAL_STATES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  VALIDATION_PENDING: 'VALIDATION_PENDING',
  ACTIVE: 'ACTIVE',
  MONITORING: 'MONITORING',
  AT_RISK: 'AT_RISK',
  INTERVENTION_REQUIRED: 'INTERVENTION_REQUIRED',
  INTERVENTION_IN_PROGRESS: 'INTERVENTION_IN_PROGRESS',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  RESOLVED: 'RESOLVED',
  RECOVERING: 'RECOVERING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
};

export const OPERATIONAL_STATE_TRANSITIONS = {
  [PROJECT_OPERATIONAL_STATES.DRAFT]: [PROJECT_OPERATIONAL_STATES.SUBMITTED],
  [PROJECT_OPERATIONAL_STATES.SUBMITTED]: [PROJECT_OPERATIONAL_STATES.VALIDATION_PENDING, PROJECT_OPERATIONAL_STATES.DRAFT],
  [PROJECT_OPERATIONAL_STATES.VALIDATION_PENDING]: [PROJECT_OPERATIONAL_STATES.ACTIVE, PROJECT_OPERATIONAL_STATES.DRAFT],
  [PROJECT_OPERATIONAL_STATES.ACTIVE]: [PROJECT_OPERATIONAL_STATES.MONITORING],
  [PROJECT_OPERATIONAL_STATES.MONITORING]: [PROJECT_OPERATIONAL_STATES.AT_RISK, PROJECT_OPERATIONAL_STATES.COMPLETED],
  [PROJECT_OPERATIONAL_STATES.AT_RISK]: [PROJECT_OPERATIONAL_STATES.INTERVENTION_REQUIRED, PROJECT_OPERATIONAL_STATES.MONITORING],
  [PROJECT_OPERATIONAL_STATES.INTERVENTION_REQUIRED]: [PROJECT_OPERATIONAL_STATES.INTERVENTION_IN_PROGRESS, PROJECT_OPERATIONAL_STATES.MONITORING],
  [PROJECT_OPERATIONAL_STATES.INTERVENTION_IN_PROGRESS]: [PROJECT_OPERATIONAL_STATES.VERIFICATION_PENDING, PROJECT_OPERATIONAL_STATES.INTERVENTION_REQUIRED],
  [PROJECT_OPERATIONAL_STATES.VERIFICATION_PENDING]: [PROJECT_OPERATIONAL_STATES.RESOLVED, PROJECT_OPERATIONAL_STATES.INTERVENTION_IN_PROGRESS],
  [PROJECT_OPERATIONAL_STATES.RESOLVED]: [PROJECT_OPERATIONAL_STATES.RECOVERING, PROJECT_OPERATIONAL_STATES.MONITORING],
  [PROJECT_OPERATIONAL_STATES.RECOVERING]: [PROJECT_OPERATIONAL_STATES.MONITORING, PROJECT_OPERATIONAL_STATES.AT_RISK, PROJECT_OPERATIONAL_STATES.COMPLETED],
  [PROJECT_OPERATIONAL_STATES.COMPLETED]: [PROJECT_OPERATIONAL_STATES.CLOSED],
  [PROJECT_OPERATIONAL_STATES.CLOSED]: [PROJECT_OPERATIONAL_STATES.ARCHIVED],
  [PROJECT_OPERATIONAL_STATES.ARCHIVED]: [],
};

// Roles allowed to authorize operational transitions
export const OPERATIONAL_TRANSITION_PERMISSIONS = {
  SUBMITTED: ['project_admin', 'system_admin', 'data_platform_security_admin'],
  VALIDATION_PENDING: ['monitoring_officer', 'system_admin', 'data_platform_security_admin'],
  ACTIVE: ['monitoring_officer', 'senior_decision_maker', 'system_admin', 'data_platform_security_admin'],
  MONITORING: ['monitoring_officer', 'system_admin', 'data_platform_security_admin'],
  AT_RISK: ['monitoring_officer', 'system_admin', 'data_platform_security_admin'],
  INTERVENTION_REQUIRED: ['monitoring_officer', 'senior_decision_maker', 'system_admin', 'data_platform_security_admin'],
  INTERVENTION_IN_PROGRESS: ['project_admin', 'monitoring_officer', 'system_admin', 'data_platform_security_admin'],
  VERIFICATION_PENDING: ['project_admin', 'system_admin', 'data_platform_security_admin'],
  RESOLVED: ['monitoring_officer', 'senior_decision_maker', 'system_admin', 'data_platform_security_admin'],
  RECOVERING: ['monitoring_officer', 'system_admin', 'data_platform_security_admin'],
  COMPLETED: ['senior_decision_maker', 'system_admin', 'monitoring_officer', 'data_platform_security_admin'],
  CLOSED: ['senior_decision_maker', 'system_admin', 'data_platform_security_admin'],
  ARCHIVED: ['system_admin', 'data_platform_security_admin'],
};

// ==============================================================================
// MONTHLY MONITORING CYCLE & UPDATE WORKFLOW STATES
// ==============================================================================
export const MONITORING_UPDATE_STATES = {
  CYCLE_OPENED: 'CYCLE_OPENED',
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  VALIDATION_PASSED: 'VALIDATION_PASSED',
  VALIDATION_FLAGGED: 'VALIDATION_FLAGGED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ACCEPTED: 'ACCEPTED',
  REJECTED_WITH_REMARKS: 'REJECTED_WITH_REMARKS',
};

// ==============================================================================
// CASE MANAGEMENT & INVESTIGATION STATES
// ==============================================================================
export const CASE_STATES = {
  OPENED: 'OPENED',
  INVESTIGATION_IN_PROGRESS: 'INVESTIGATION_IN_PROGRESS',
  ACTION_PLAN_SUBMITTED: 'ACTION_PLAN_SUBMITTED',
  ACTION_PLAN_APPROVED: 'ACTION_PLAN_APPROVED',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  FIELD_VERIFICATION_PENDING: 'FIELD_VERIFICATION_PENDING',
  VERIFIED_RESOLVED: 'VERIFIED_RESOLVED',
  ESCALATED: 'ESCALATED',
  CLOSED: 'CLOSED',
};

// ==============================================================================
// SENIOR DECISION MAKER WORKFLOW STATES
// ==============================================================================
export const DECISION_STATES = {
  BRIEF_PREPARED: 'BRIEF_PREPARED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  OPTION_SELECTED: 'OPTION_SELECTED',
  APPROVED: 'APPROVED',
  DIRECTIVE_ISSUED: 'DIRECTIVE_ISSUED',
  EXECUTED: 'EXECUTED',
};

// Valid transitions for Project Risk Lifecycle
export const RISK_STATE_TRANSITIONS = {
  [PROJECT_RISK_STATES.ON_TRACK]: [PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.AT_RISK],
  [PROJECT_RISK_STATES.WATCH]: [PROJECT_RISK_STATES.ON_TRACK, PROJECT_RISK_STATES.AT_RISK, PROJECT_RISK_STATES.HIGH_RISK],
  [PROJECT_RISK_STATES.AT_RISK]: [PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.HIGH_RISK, PROJECT_RISK_STATES.CRITICAL],
  [PROJECT_RISK_STATES.HIGH_RISK]: [PROJECT_RISK_STATES.CRITICAL, PROJECT_RISK_STATES.INTERVENTION, PROJECT_RISK_STATES.RECOVERY],
  [PROJECT_RISK_STATES.CRITICAL]: [PROJECT_RISK_STATES.INTERVENTION, PROJECT_RISK_STATES.HIGH_RISK],
  [PROJECT_RISK_STATES.INTERVENTION]: [PROJECT_RISK_STATES.RECOVERY, PROJECT_RISK_STATES.CRITICAL],
  [PROJECT_RISK_STATES.RECOVERY]: [PROJECT_RISK_STATES.ON_TRACK, PROJECT_RISK_STATES.WATCH, PROJECT_RISK_STATES.AT_RISK],
};

// Valid transitions for Action Workflow Lifecycle
export const ACTION_STATE_TRANSITIONS = {
  [ACTION_STATES.RISK_DETECTED]: [ACTION_STATES.RECOMMENDED, ACTION_STATES.ACTION_ASSIGNED],
  [ACTION_STATES.RECOMMENDED]: [ACTION_STATES.ACTION_ASSIGNED, ACTION_STATES.RESOLVED],
  [ACTION_STATES.ACTION_ASSIGNED]: [ACTION_STATES.IN_PROGRESS, ACTION_STATES.RECOMMENDED],
  [ACTION_STATES.IN_PROGRESS]: [ACTION_STATES.EVIDENCE_SUBMITTED, ACTION_STATES.OFFICER_REVIEW, ACTION_STATES.RESOLVED],
  [ACTION_STATES.EVIDENCE_SUBMITTED]: [ACTION_STATES.OFFICER_REVIEW, ACTION_STATES.RESOLVED, ACTION_STATES.IN_PROGRESS],
  [ACTION_STATES.OFFICER_REVIEW]: [ACTION_STATES.RESOLVED, ACTION_STATES.IN_PROGRESS],
  [ACTION_STATES.RESOLVED]: [ACTION_STATES.RECALCULATED],
  [ACTION_STATES.RECALCULATED]: [ACTION_STATES.ACTION_ASSIGNED, ACTION_STATES.RESOLVED],
};

/**
 * Computes the recommended risk state from numerical telemetry
 */
export const evaluateProjectRiskState = (project) => {
  const costGrowth = Number(project.cost_growth_pct || 0);
  const extensionMonths = Number(project.schedule_extension_months || 0);
  const progress = Number(project.physical_progress || 0);

  if (costGrowth > 100 || extensionMonths > 36) {
    return PROJECT_RISK_STATES.CRITICAL;
  }
  if (costGrowth > 40 || extensionMonths > 18) {
    return PROJECT_RISK_STATES.HIGH_RISK;
  }
  if (costGrowth > 15 || extensionMonths > 6) {
    return PROJECT_RISK_STATES.AT_RISK;
  }
  if (costGrowth > 0 || progress < 50) {
    return PROJECT_RISK_STATES.WATCH;
  }
  return PROJECT_RISK_STATES.ON_TRACK;
};
