// ==============================================================================
// PAIMANA PREDICT — USER & STRICT RBAC DOMAIN MODELS
// ==============================================================================

export const ROLES = {
  MONITORING_OFFICER: 'monitoring_officer',
  PROJECT_ADMIN: 'project_admin',
  SYSTEM_ADMIN: 'system_admin',
  DATA_ANALYST: 'risk_analyst',
  DECISION_MAKER: 'senior_decision_maker',
  QUALITY_AUDITOR: 'quality_auditor',
  FINANCIAL_OFFICER: 'financial_officer',
  CONTRACTOR_REP: 'contractor_rep',
  GATISHAKTI_OFFICER: 'gatishakti_officer',
  DATA_OFFICER: 'data_officer',
  AI_GOVERNANCE: 'ai_governance',
  SECURITY_OFFICER: 'security_officer',
};

// Aliases mapping for backward compatibility
export const ROLE_ALIASES = {
  'MONITORING_OFFICER': 'monitoring_officer',
  'monitoring_officer': 'monitoring_officer',
  'PROJECT_ADMIN': 'project_admin',
  'project_admin': 'project_admin',
  'SYSTEM_ADMIN': 'system_admin',
  'system_admin': 'system_admin',
  'DATA_ANALYST': 'risk_analyst',
  'risk_analyst': 'risk_analyst',
  'DECISION_MAKER': 'senior_decision_maker',
  'senior_decision_maker': 'senior_decision_maker',
  'QUALITY_AUDITOR': 'quality_auditor',
  'quality_auditor': 'quality_auditor',
  'quality': 'quality_auditor',
  'auditor': 'quality_auditor',
  'FINANCIAL_OFFICER': 'financial_officer',
  'financial_officer': 'financial_officer',
  'finance': 'financial_officer',
  'CONTRACTOR_REP': 'contractor_rep',
  'contractor_rep': 'contractor_rep',
  'contractor': 'contractor_rep',
  'GATISHAKTI_OFFICER': 'gatishakti_officer',
  'gatishakti_officer': 'gatishakti_officer',
  'gatishakti': 'gatishakti_officer',
  'DATA_OFFICER': 'data_officer',
  'data_officer': 'data_officer',
  'data': 'data_officer',
  'document': 'data_officer',
  'AI_GOVERNANCE': 'ai_governance',
  'ai_governance': 'ai_governance',
  'aigov': 'ai_governance',
  'approver': 'ai_governance',
  'SECURITY_OFFICER': 'security_officer',
  'security_officer': 'security_officer',
  'security': 'security_officer',
};

export const PERMISSIONS = {
  // Common / Dashboard
  DASHBOARD_VIEW: 'dashboard.view',
  EXECUTIVE_DASHBOARD_VIEW: 'executive_dashboard.view',
  PORTFOLIO_VIEW: 'portfolio.view',
  PROJECTS_VIEW: 'projects.view',
  RISK_VIEW: 'risk.view',
  AI_ASSISTANT_USE: 'ai_assistant.use',

  // 1. Monitoring Officer (Surveillance & Signals)
  WARNINGS_VIEW: 'warnings.view',
  WARNINGS_ACKNOWLEDGE: 'warnings.acknowledge',
  INTERVENTIONS_ASSIGN: 'interventions.assign',
  INTERVENTIONS_MONITOR: 'interventions.monitor',
  SIGNALS_VIEW: 'signals.view',
  RISK_NETWORK_VIEW: 'risk_network.view',
  BRIEFS_GENERATE: 'briefs.generate',
  MONITORING_REMARKS_ADD: 'monitoring.remarks.add',
  PROJECT_ESCALATE: 'project.escalate',

  // 2. Project Administrator (Progress Update & Response)
  PROJECTS_ASSIGNED_VIEW: 'projects.assigned.view',
  PROGRESS_UPDATE: 'progress.update',
  MILESTONES_UPDATE: 'milestones.update',
  EXPENDITURE_UPDATE: 'expenditure.update',
  DELAY_REASON_SUBMIT: 'delay.reason.submit',
  EVIDENCE_UPLOAD: 'evidence.upload',
  INTERVENTION_RESPOND: 'intervention.respond',
  WARNINGS_ASSIGNED_VIEW: 'warnings.assigned.view',
  PREDICTIONS_ASSIGNED_VIEW: 'predictions.assigned.view',

  // 3. System Administrator (Admin & Audit Trail)
  SYSTEM_VIEW: 'system.view',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_MANAGE: 'permissions.manage',
  AUDIT_VIEW: 'audit.view',
  CONFIGURATION_MANAGE: 'configuration.manage',
  INGESTION_INSPECT: 'ingestion.inspect',
  HEALTH_INSPECT: 'health.inspect',
  SECURITY_LOGS_VIEW: 'security_logs.view',

  // 4. Risk / Data Analyst (ML Models & Trends)
  PREDICTIONS_VIEW: 'predictions.view',
  MODELS_VIEW: 'models.view',
  ANALYTICS_VIEW: 'analytics.view',
  BACKTESTING_RUN: 'backtesting.run',
  DRIFT_VIEW: 'drift.view',
  FEATURES_INSPECT: 'features.inspect',
  ANOMALIES_INSPECT: 'anomalies.inspect',
  BENCHMARKING_VIEW: 'benchmarking.view',
  MODELS_COMPARE: 'models.compare',

  // 5. Senior Decision Maker (Executive Portfolio Brief)
  HIGH_RISK_VIEW: 'high_risk.view',
  CRITICAL_PROJECTS_VIEW: 'critical_projects.view',
  EXPOSURE_VIEW: 'exposure.view',
  REPORTS_GENERATE: 'reports.generate',
  EXECUTIVE_BRIEF_VIEW: 'executive_brief.view',
  SECTOR_RISK_VIEW: 'sector_risk.view',

  // 6. Quality Auditor & TPI Engineer (Quality & Compliance)
  QUALITY_VIEW: 'quality.view',
  QUALITY_NCR_RAISE: 'quality.ncr.raise',
  QUALITY_NCR_VERIFY: 'quality.ncr.verify',
  QUALITY_LAB_RECORD: 'quality.lab.record',
  QUALITY_PHOTOS_VERIFY: 'quality.photos.verify',

  // 7. Financial Adviser (IFD / Capital Outlay)
  FINANCE_VIEW: 'finance.view',
  EXPENDITURE_AUDIT: 'expenditure.audit',
  SANCTION_VERIFY: 'sanction.verify',
  RCE_EVALUATE: 'rce.evaluate',

  // 8. Contractor / EPC Project Director (Construction Field Hub)
  CONTRACTOR_EXECUTE: 'contractor.execute',
  REWORK_SUBMIT: 'rework.submit',
  LAB_REPORT_UPLOAD: 'lab_report.upload',

  // 9. PM GatiShakti Nodal Coordinator (Network Sync & Clearances)
  DEPENDENCY_SURVEIL: 'dependency.surveil',
  ROW_COORDINATE: 'row.coordinate',
  CASCADE_SIMULATE: 'cascade.simulate',
  DIRECTIVE_DISPATCH: 'directive.dispatch',

  // 10. Data & Document Ingestion Officer
  DATA_INGESTION_MANAGE: 'data_ingestion.manage',
  SCHEMA_MANAGE: 'schema.manage',
  IMPORT_COMMIT: 'import.commit',
  DOCUMENT_VERIFY: 'document.verify',

  // 11. AI Governance Approver
  MODEL_APPROVE: 'model.approve',
  DRIFT_SIGNOFF: 'drift.signoff',
  MODEL_AUDIT_VERIFY: 'model_audit.verify',
  EXPLAINABILITY_INSPECT: 'explainability.inspect',

  // 12. Security & Platform Officer
  SECURITY_AUDIT_VIEW: 'security_audit.view',
  ACCESS_CONTROL_INSPECT: 'access_control.inspect',
  INCIDENT_LOG_MANAGE: 'incident_log.manage',
  TOKEN_POLICY_ENFORCE: 'token_policy.enforce',
};

export const ROLE_PERMISSIONS = {
  [ROLES.MONITORING_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.WARNINGS_VIEW,
    PERMISSIONS.WARNINGS_ACKNOWLEDGE,
    PERMISSIONS.INTERVENTIONS_ASSIGN,
    PERMISSIONS.INTERVENTIONS_MONITOR,
    PERMISSIONS.SIGNALS_VIEW,
    PERMISSIONS.RISK_NETWORK_VIEW,
    PERMISSIONS.BRIEFS_GENERATE,
    PERMISSIONS.MONITORING_REMARKS_ADD,
    PERMISSIONS.PROJECT_ESCALATE,
    PERMISSIONS.AI_ASSISTANT_USE,
    // Backward-compat keys
    'view:portfolio', 'investigate:projects', 'view:risks', 'review:warnings', 'acknowledge:warnings', 'assign:interventions', 'generate:briefs', 'monitor:actions'
  ],

  [ROLES.PROJECT_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROJECTS_ASSIGNED_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PROGRESS_UPDATE,
    PERMISSIONS.MILESTONES_UPDATE,
    PERMISSIONS.EXPENDITURE_UPDATE,
    PERMISSIONS.DELAY_REASON_SUBMIT,
    PERMISSIONS.EVIDENCE_UPLOAD,
    PERMISSIONS.INTERVENTION_RESPOND,
    PERMISSIONS.WARNINGS_ASSIGNED_VIEW,
    PERMISSIONS.PREDICTIONS_ASSIGNED_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    // Backward-compat keys
    'view:assigned_projects', 'update:progress', 'update:milestones', 'respond:warnings', 'update:actions'
  ],

  [ROLES.SYSTEM_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SYSTEM_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.PERMISSIONS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.CONFIGURATION_MANAGE,
    PERMISSIONS.INGESTION_INSPECT,
    PERMISSIONS.HEALTH_INSPECT,
    PERMISSIONS.SECURITY_LOGS_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    // Backward-compat keys
    'manage:users', 'assign:roles', 'configure:settings', 'inspect:ingestion', 'inspect:models', 'inspect:audit', 'inspect:health', 'view:portfolio', 'investigate:projects'
  ],

  [ROLES.DATA_ANALYST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.PREDICTIONS_VIEW,
    PERMISSIONS.MODELS_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.BACKTESTING_RUN,
    PERMISSIONS.DRIFT_VIEW,
    PERMISSIONS.FEATURES_INSPECT,
    PERMISSIONS.ANOMALIES_INSPECT,
    PERMISSIONS.BENCHMARKING_VIEW,
    PERMISSIONS.MODELS_COMPARE,
    PERMISSIONS.RISK_NETWORK_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    // Backward-compat keys
    'inspect:datasets', 'analyze:trends', 'inspect:anomalies', 'compare:models', 'inspect:features', 'monitor:performance', 'review:quality', 'view:portfolio'
  ],

  [ROLES.DECISION_MAKER]: [
    PERMISSIONS.EXECUTIVE_DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.HIGH_RISK_VIEW,
    PERMISSIONS.CRITICAL_PROJECTS_VIEW,
    PERMISSIONS.EXPOSURE_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.EXECUTIVE_BRIEF_VIEW,
    PERMISSIONS.SECTOR_RISK_VIEW,
    PERMISSIONS.BENCHMARKING_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    // Backward-compat keys
    'view:portfolio', 'view:critical_projects', 'view:sector_risk', 'view:exposure', 'view:priority_interventions', 'view:executive_briefs'
  ],

  [ROLES.QUALITY_AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.QUALITY_VIEW,
    PERMISSIONS.QUALITY_NCR_RAISE,
    PERMISSIONS.QUALITY_NCR_VERIFY,
    PERMISSIONS.QUALITY_LAB_RECORD,
    PERMISSIONS.QUALITY_PHOTOS_VERIFY,
    PERMISSIONS.AI_ASSISTANT_USE,
    'view:quality', 'raise:ncr', 'verify:ncr', 'record:lab_tests', 'verify:photos'
  ],

  [ROLES.FINANCIAL_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.EXPENDITURE_AUDIT,
    PERMISSIONS.SANCTION_VERIFY,
    PERMISSIONS.RCE_EVALUATE,
    PERMISSIONS.EXPOSURE_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    'view:financials', 'audit:expenditure', 'evaluate:cost_growth', 'approve:rce'
  ],

  [ROLES.CONTRACTOR_REP]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROJECTS_ASSIGNED_VIEW,
    PERMISSIONS.CONTRACTOR_EXECUTE,
    PERMISSIONS.REWORK_SUBMIT,
    PERMISSIONS.LAB_REPORT_UPLOAD,
    PERMISSIONS.EVIDENCE_UPLOAD,
    PERMISSIONS.AI_ASSISTANT_USE,
    'submit:progress_claim', 'submit:rework', 'upload:evidence', 'upload:lab_test'
  ],

  [ROLES.GATISHAKTI_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.DEPENDENCY_SURVEIL,
    PERMISSIONS.ROW_COORDINATE,
    PERMISSIONS.CASCADE_SIMULATE,
    PERMISSIONS.DIRECTIVE_DISPATCH,
    PERMISSIONS.RISK_NETWORK_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    'view:dependencies', 'coordinate:row', 'track:utilities', 'issue:directives'
  ],

  [ROLES.DATA_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.DATA_INGESTION_MANAGE,
    PERMISSIONS.SCHEMA_MANAGE,
    PERMISSIONS.IMPORT_COMMIT,
    PERMISSIONS.DOCUMENT_VERIFY,
    PERMISSIONS.INGESTION_INSPECT,
    PERMISSIONS.AI_ASSISTANT_USE,
    'manage:ingestion', 'verify:documents', 'commit:imports', 'view:schemas'
  ],

  [ROLES.AI_GOVERNANCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PORTFOLIO_VIEW,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.MODELS_VIEW,
    PERMISSIONS.MODEL_APPROVE,
    PERMISSIONS.DRIFT_SIGNOFF,
    PERMISSIONS.MODEL_AUDIT_VERIFY,
    PERMISSIONS.EXPLAINABILITY_INSPECT,
    PERMISSIONS.PREDICTIONS_VIEW,
    PERMISSIONS.DRIFT_VIEW,
    PERMISSIONS.BENCHMARKING_VIEW,
    PERMISSIONS.AI_ASSISTANT_USE,
    'approve:models', 'signoff:drift', 'audit:model_cards', 'inspect:explainability'
  ],

  [ROLES.SECURITY_OFFICER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.SYSTEM_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_LOGS_VIEW,
    PERMISSIONS.SECURITY_AUDIT_VIEW,
    PERMISSIONS.ACCESS_CONTROL_INSPECT,
    PERMISSIONS.INCIDENT_LOG_MANAGE,
    PERMISSIONS.TOKEN_POLICY_ENFORCE,
    PERMISSIONS.HEALTH_INSPECT,
    PERMISSIONS.AI_ASSISTANT_USE,
    'inspect:audit', 'view:security_logs', 'audit:access_control', 'inspect:health'
  ],
};

// Seed Authorized Operational Users for All Roles
export const SEED_USERS = [
  {
    id: 'usr-officer-01',
    username: 'officer',
    aliases: ['officer', 'monitoring_officer', 'monitoring', 'priya'],
    passwordHash: 'officer123',
    fullName: 'Priya Iyer',
    email: 'priya.monitoring@mospi.gov.in',
    role: ROLES.MONITORING_OFFICER,
    roles: [ROLES.MONITORING_OFFICER],
    defaultWorkspace: '/',
    department: 'MoSPI Project Monitoring Division',
    designation: 'Joint Director (Surveillance)',
    assignedProjects: ['ALL_SURVEILLANCE'],
  },
  {
    id: 'usr-nodal-01',
    username: 'nodal',
    aliases: ['nodal', 'project_admin', 'projadmin', 'admin_bbnl', 'amitabh'],
    passwordHash: 'nodal123',
    fullName: 'Amitabh Verma',
    email: 'amitabh.verma@bbnl.gov.in',
    role: ROLES.PROJECT_ADMIN,
    roles: [ROLES.PROJECT_ADMIN],
    defaultWorkspace: '/projects/PAI-706775',
    department: 'Bharat Broadband Network Ltd (BBNL)',
    designation: 'Chief Project General Manager',
    assignedProjects: ['PAI-706775', '706775'], // BharatNet assigned
  },
  {
    id: 'usr-sysadmin-01',
    username: 'sysadmin',
    aliases: ['sysadmin', 'system_admin', 'admin', 'rajesh'],
    passwordHash: 'sysadmin123',
    fullName: 'Rajesh Sharma',
    email: 'sysadmin.infra@gov.in',
    role: ROLES.SYSTEM_ADMIN,
    roles: [ROLES.SYSTEM_ADMIN],
    defaultWorkspace: '/settings',
    department: 'PMO Infrastructure Cell',
    designation: 'Director (System Administration)',
    assignedProjects: ['ALL_SYSTEM_ADMIN'],
  },
  {
    id: 'usr-analyst-01',
    username: 'analyst',
    aliases: ['analyst', 'risk_analyst', 'data_analyst', 'neha'],
    passwordHash: 'analyst123',
    fullName: 'Dr. Neha Kulkarni',
    email: 'neha.analyst@niti.gov.in',
    role: ROLES.DATA_ANALYST,
    roles: [ROLES.DATA_ANALYST],
    defaultWorkspace: '/predictions',
    department: 'NITI Aayog Data Analytics Unit',
    designation: 'Lead Infrastructure Data Scientist',
    assignedProjects: ['ALL_ANALYTICS'],
  },
  {
    id: 'usr-secretary-01',
    username: 'secretary',
    aliases: ['secretary', 'senior_decision_maker', 'decision_maker', 'sundaram'],
    passwordHash: 'secretary123',
    fullName: 'V. K. Sundaram',
    email: 'secretary.infra@cabinet.gov.in',
    role: ROLES.DECISION_MAKER,
    roles: [ROLES.DECISION_MAKER],
    defaultWorkspace: '/risk-intelligence',
    department: 'Cabinet Secretariat / Prime Minister Office',
    designation: 'Secretary (Infrastructure & Coordination)',
    assignedProjects: ['ALL_PORTFOLIO_CRITICAL'],
  },
  {
    id: 'usr-quality-01',
    username: 'quality',
    aliases: ['quality', 'quality_auditor', 'auditor', 'inspector', 'vikram'],
    passwordHash: 'quality123',
    fullName: 'Er. Vikramaditya Rathore',
    email: 'vikram.quality@eil.gov.in',
    role: ROLES.QUALITY_AUDITOR,
    roles: [ROLES.QUALITY_AUDITOR],
    defaultWorkspace: '/quality',
    department: 'Engineers India Limited (EIL) / TPI Agency',
    designation: 'Chief Quality Auditor & Lead Independent Engineer',
    assignedProjects: ['ALL_QUALITY_AUDITS'],
  },
  {
    id: 'usr-finance-01',
    username: 'finance',
    aliases: ['finance', 'financial_officer', 'fa', 'budget', 'meenakshi'],
    passwordHash: 'finance123',
    fullName: 'Smt. Meenakshi Sundaram',
    email: 'meenakshi.fa@finmin.nic.in',
    role: ROLES.FINANCIAL_OFFICER,
    roles: [ROLES.FINANCIAL_OFFICER],
    defaultWorkspace: '/analytics',
    department: 'Integrated Finance Division (IFD), MoF & MoSPI',
    designation: 'Joint Secretary & Financial Adviser (JS&FA)',
    assignedProjects: ['ALL_FINANCIAL_AUDITS'],
  },
  {
    id: 'usr-contractor-01',
    username: 'contractor',
    aliases: ['contractor', 'contractor_rep', 'epc', 'harish'],
    passwordHash: 'contractor123',
    fullName: 'Harish Chandra',
    email: 'harish.epc@ltinfra.com',
    role: ROLES.CONTRACTOR_REP,
    roles: [ROLES.CONTRACTOR_REP],
    defaultWorkspace: '/projects/PAI-706775',
    department: 'L&T Infrastructure / BharatNet EPC Consortium',
    designation: 'Project Director & EPC Consortium Lead',
    assignedProjects: ['PAI-706775', '706775'],
  },
  {
    id: 'usr-gatishakti-01',
    username: 'gatishakti',
    aliases: ['gatishakti', 'gatishakti_officer', 'npg', 'ramanathan'],
    passwordHash: 'gatishakti123',
    fullName: 'K. R. Ramanathan',
    email: 'ramanathan.npg@dpiit.gov.in',
    role: ROLES.GATISHAKTI_OFFICER,
    roles: [ROLES.GATISHAKTI_OFFICER],
    defaultWorkspace: '/risk-network',
    department: 'Network Planning Group (NPG), PM GatiShakti / DPIIT',
    designation: 'Director (Inter-Ministerial Infrastructure Logistics)',
    assignedProjects: ['ALL_GATISHAKTI_CORRIDORS'],
  },
  {
    id: 'usr-data-01',
    username: 'dataofficer',
    aliases: ['dataofficer', 'data', 'document', 'sunil'],
    passwordHash: 'data123',
    fullName: 'Sunil Mehra',
    email: 'sunil.data@mospi.gov.in',
    role: ROLES.DATA_OFFICER,
    roles: [ROLES.DATA_OFFICER],
    defaultWorkspace: '/imports',
    department: 'MoSPI Data & Survey Architecture Division',
    designation: 'Director (Data Ingestion & Documentation)',
    assignedProjects: ['ALL_DATA_INGESTION'],
  },
  {
    id: 'usr-aigov-01',
    username: 'aigov',
    aliases: ['aigov', 'approver', 'ai_governance', 'aruna'],
    passwordHash: 'aigov123',
    fullName: 'Dr. Aruna Chandrasekhar',
    email: 'aruna.aigov@meity.gov.in',
    role: ROLES.AI_GOVERNANCE,
    roles: [ROLES.AI_GOVERNANCE],
    defaultWorkspace: '/predictions',
    department: 'MeitY & NITI Aayog AI Validation Committee',
    designation: 'Chair (AI Ethics & Model Validation Committee)',
    assignedProjects: ['ALL_MODEL_GOVERNANCE'],
  },
  {
    id: 'usr-security-01',
    username: 'security',
    aliases: ['security', 'security_officer', 'ciso', 'sanjeev'],
    passwordHash: 'security123',
    fullName: 'Col. Sanjeev Nair',
    email: 'sanjeev.security@cert-in.gov.in',
    role: ROLES.SECURITY_OFFICER,
    roles: [ROLES.SECURITY_OFFICER],
    defaultWorkspace: '/settings',
    department: 'CERT-In / National Infrastructure Protection',
    designation: 'Chief Information Security Officer (CISO)',
    assignedProjects: ['ALL_SYSTEM_AUDITS'],
  },
  {
    id: 'usr-multi-01',
    username: 'multirole',
    aliases: ['multirole', 'joint', 'murthy'],
    passwordHash: 'multi123',
    fullName: 'Dr. K. S. Murthy',
    email: 'joint.officer@gov.in',
    role: ROLES.MONITORING_OFFICER,
    roles: [ROLES.MONITORING_OFFICER, ROLES.PROJECT_ADMIN],
    defaultWorkspace: '/',
    department: 'MoSPI & BBNL Joint Infrastructure Cell',
    designation: 'Joint Director & Project Execution Coordinator',
    assignedProjects: ['ALL_SURVEILLANCE', 'PAI-706775'],
  },
];
