import { Project } from '../types/project';
import { RiskNode, RiskEdge, RiskPropagationChain } from '../types/riskNetwork';

class RiskNetworkService {
  /**
   * Generates a multi-branch propagation network for a specific project.
   */
  public getPropagationChain(project: Project): RiskPropagationChain {
    if (project.project_id === 'PJ-1042') {
      return this.getHeroPropagationChain(project);
    }

    return this.generateDynamicPropagationChain(project);
  }

  private getHeroPropagationChain(project: Project): RiskPropagationChain {
    const nodes: RiskNode[] = [
      // 1. Root Causes
      {
        id: 'node-root-land',
        label: 'Land Acquisition & RoW Deficit',
        category: 'Root Cause',
        type: 'ROOT_CAUSE',
        severity: 'CRITICAL',
        currentValue: '52% Acquired',
        expectedValue: '90% Target Baseline',
        variance: '-38% Deficit',
        impactPoints: 18,
        evidence: 'Court stays and compensation award delays across 42 parcels along the 34km Chandauli-Bhabua corridor.',
        explanation: 'Incomplete Right-of-Way prevents continuous formation earthworks and track-laying machine access.',
        timeDelayEffect: '+3.5 to 4.5 months direct critical path civil delay.',
        costEscalationEffect: 'Contractor machinery idling claims at ₹2.5 Cr/month.',
        mitigation: 'Release ₹140 Cr supplementary escrow to District Revenue Collectors for expedited compensation settlement.',
        downstreamEffects: ['node-inter-civil', 'node-inter-idle'],
        x: 120,
        y: 80,
      },
      {
        id: 'node-root-utility',
        label: 'Utility Relocation Bottleneck',
        category: 'Root Cause',
        type: 'ROOT_CAUSE',
        severity: 'HIGH',
        currentValue: 'Critical Delay',
        expectedValue: 'Clearance Completed',
        variance: '>120 Days Overdue',
        impactPoints: 8,
        evidence: '3 high-tension 400kV PowerGrid line crossings pending shutdown window clearances.',
        explanation: 'Power lines cross directly over bridge launch piers, preventing heavy crane setup.',
        timeDelayEffect: '+2.0 months delay on superstructure erection.',
        costEscalationEffect: 'Crane remobilization charges and contractor variation notices.',
        mitigation: 'Convene State Level Power Committee to sanction staggered weekend shutdown permits.',
        downstreamEffects: ['node-inter-civil'],
        x: 120,
        y: 280,
      },
      {
        id: 'node-root-exp',
        label: 'Contractor Variation Bill Delays',
        category: 'Root Cause',
        type: 'ROOT_CAUSE',
        severity: 'HIGH',
        currentValue: '58% Expended',
        expectedValue: '76% Planned Cash Flow',
        variance: '-18% Capital Lag',
        impactPoints: 11,
        evidence: 'Withheld price escalation bills due to steel price adjustment dispute.',
        explanation: 'Delayed payments reduce contractor working capital and on-site workforce shifts.',
        timeDelayEffect: '+1.5 months secondary execution drag.',
        costEscalationEffect: 'Dispute interest penalties.',
        mitigation: 'Release 75% ad-hoc provisional payment against undisputed variation bills.',
        downstreamEffects: ['node-inter-milestone'],
        x: 120,
        y: 480,
      },

      // 2. Intermediate Effects
      {
        id: 'node-inter-civil',
        label: 'Subgrade & Civil Work Stoppage',
        category: 'Intermediate Effect',
        type: 'INTERMEDIATE_EFFECT',
        severity: 'CRITICAL',
        currentValue: '61% Physical Progress',
        expectedValue: '76% Planned Progress',
        variance: '-15% Execution Gap',
        impactPoints: 12,
        evidence: 'Mechanized track-laying trains (NTC) running at 30% utilization.',
        explanation: 'Track bed formation interrupted at missing land parcels.',
        timeDelayEffect: 'Cascades directly into intermediate milestone deadlines.',
        costEscalationEffect: 'Idle equipment depreciation.',
        mitigation: 'Crash subgrade civil works using double-shift contractor operations.',
        downstreamEffects: ['node-inter-milestone', 'node-inter-idle'],
        x: 420,
        y: 160,
      },
      {
        id: 'node-inter-idle',
        label: 'Machinery & Resource Idle Time',
        category: 'Intermediate Effect',
        type: 'INTERMEDIATE_EFFECT',
        severity: 'HIGH',
        currentValue: '45 Days Idling',
        expectedValue: 'Zero Unplanned Idling',
        variance: '+45 Days Disruption',
        impactPoints: 6,
        evidence: 'Heavy cranes and track tampers parked on site without access clearances.',
        explanation: 'Contractors incurring statutory overheads while waiting for site clearances.',
        timeDelayEffect: 'Loss of optimal pre-monsoon construction season.',
        costEscalationEffect: 'Contractor variation claims accumulating at ₹35 Cr.',
        mitigation: 'Reallocate machinery to cleared brownfield sections.',
        downstreamEffects: ['node-down-overhead'],
        x: 420,
        y: 340,
      },
      {
        id: 'node-inter-milestone',
        label: '3 Consecutive Milestone Slippages',
        category: 'Intermediate Effect',
        type: 'INTERMEDIATE_EFFECT',
        severity: 'CRITICAL',
        currentValue: '3 Delayed Milestones',
        expectedValue: '0 Milestones Delayed',
        variance: '3 Critical Delays',
        impactPoints: 14,
        evidence: 'Track laying, Traction Substations, and Signaling Interlocking past revision dates.',
        explanation: 'Failure of sequential critical path milestones breaks integrated commissioning schedule.',
        timeDelayEffect: 'Critical path slippage accumulating at 0.8 months per quarter.',
        costEscalationEffect: 'Extended supervision consultancy fees.',
        mitigation: 'Deploy parallel signaling installation crews ahead of track certification.',
        downstreamEffects: ['node-down-schedule'],
        x: 420,
        y: 500,
      },

      // 3. Downstream Consequences
      {
        id: 'node-down-schedule',
        label: 'Commercial COD Schedule Extension',
        category: 'Downstream Consequence',
        type: 'DOWNSTREAM_CONSEQUENCE',
        severity: 'CRITICAL',
        currentValue: 'Nov 2026 COD',
        expectedValue: 'Dec 2025 Original COD',
        variance: '+7 Months Slippage',
        impactPoints: 15,
        evidence: 'Expected completion date extended across statutory project monitoring filings.',
        explanation: 'Overall commissioning date slips into subsequent financial year.',
        timeDelayEffect: '+7 months total schedule extension.',
        costEscalationEffect: 'Financing interest during construction (IDC) escalation of ₹180 Cr.',
        mitigation: 'Implement 24/7 commissioning blitz upon completion of civil packages.',
        downstreamEffects: ['node-term-cost'],
        x: 720,
        y: 240,
      },
      {
        id: 'node-down-overhead',
        label: 'Overhead & Extended Supervision Inflation',
        category: 'Downstream Consequence',
        type: 'DOWNSTREAM_CONSEQUENCE',
        severity: 'HIGH',
        currentValue: '+₹115 Cr Overhead',
        expectedValue: 'Budgeted Overhead',
        variance: '+22% Administrative Cost',
        impactPoints: 8,
        evidence: 'Prolonged deployment of general consultant and site management personnel.',
        explanation: 'Fixed project administration costs scale linearly with gestation period.',
        timeDelayEffect: 'N/A',
        costEscalationEffect: 'Adds ~₹15 Cr per additional quarter of project gestation.',
        mitigation: 'Freeze non-essential administrative expenditures.',
        downstreamEffects: ['node-term-cost'],
        x: 720,
        y: 440,
      },

      // 4. Terminal Impact
      {
        id: 'node-term-cost',
        label: 'Terminal Capital Cost Overrun',
        category: 'Terminal Impact',
        type: 'TERMINAL_IMPACT',
        severity: 'CRITICAL',
        currentValue: '₹9,180 Cr Revised Cost',
        expectedValue: '₹8,450 Cr Original Cost',
        variance: '+₹730 Cr Exposure',
        impactPoints: 20,
        evidence: 'Compounded total of price indexation, variation awards, IDC, and overhead extensions.',
        explanation: 'Terminal budgetary escalation requiring supplementary cabinet approval.',
        timeDelayEffect: 'Terminal outcome of cumulative schedule slippages.',
        costEscalationEffect: 'Total predicted capital exposure of ₹730 Cr (78% probability).',
        mitigation: 'Submit comprehensive Revised Cost Estimate (RCE) to Cabinet Committee on Economic Affairs.',
        downstreamEffects: [],
        x: 1000,
        y: 320,
      },
    ];

    const edges: RiskEdge[] = [
      { id: 'e1', source: 'node-root-land', target: 'node-inter-civil', label: 'Blocks RoW' },
      { id: 'e2', source: 'node-root-land', target: 'node-inter-idle', label: 'Halts Machines' },
      { id: 'e3', source: 'node-root-utility', target: 'node-inter-civil', label: 'Blocks Crane Setup' },
      { id: 'e4', source: 'node-root-exp', target: 'node-inter-milestone', label: 'Cash Flow Strain' },
      { id: 'e5', source: 'node-inter-civil', target: 'node-inter-milestone', label: 'Pushes Deliverables' },
      { id: 'e6', source: 'node-inter-civil', target: 'node-inter-idle', label: 'Equipment Idling' },
      { id: 'e7', source: 'node-inter-idle', target: 'node-down-overhead', label: 'Adds Overhead' },
      { id: 'e8', source: 'node-inter-milestone', target: 'node-down-schedule', label: 'Extends COD' },
      { id: 'e9', source: 'node-down-schedule', target: 'node-term-cost', label: 'IDC & Price Escalation' },
      { id: 'e10', source: 'node-down-overhead', target: 'node-term-cost', label: 'Compounded Escalation' },
    ];

    return {
      projectId: project.project_id,
      projectName: project.project_name,
      rootCausesCount: 3,
      downstreamRisksCount: 5,
      estimatedCostExposureCr: project.predicted_cost_overrun,
      estimatedDelayMonths: project.predicted_delay_months,
      summaryNarrative:
        'Current risk concentration demonstrates how unresolved Right-of-Way and high-tension utility clearances propagate directly through civil progress into 3 delayed milestones, compounding into a 7-month COD extension and ₹730 Cr terminal cost exposure.',
      nodes,
      edges,
    };
  }

  private generateDynamicPropagationChain(project: Project): RiskPropagationChain {
    const isCritical = project.risk_score >= 75;
    const isHigh = project.risk_score >= 50;

    const nodes: RiskNode[] = [
      {
        id: 'dyn-root-1',
        label: project.land_progress < project.land_target ? 'Land Handover & RoW Deficit' : 'Statutory Approval Lag',
        category: 'Root Cause',
        type: 'ROOT_CAUSE',
        severity: project.land_progress < 70 ? 'CRITICAL' : 'HIGH',
        currentValue: `${project.land_progress}% Progress`,
        expectedValue: `${project.land_target}% Target`,
        variance: `-${project.land_target - project.land_progress}% Deficit`,
        impactPoints: 16,
        evidence: `Operational status reported with ${project.land_target - project.land_progress}% gap against planned target.`,
        explanation: 'Early statutory or Right-of-Way friction slowing initial mobilization.',
        timeDelayEffect: `Drives ~${Math.max(1, Math.round(project.predicted_delay_months * 0.4))} months initial slippage.`,
        costEscalationEffect: 'Escalates early preparatory overheads.',
        mitigation: 'Convene district coordination taskforce for expedited clearances.',
        downstreamEffects: ['dyn-inter-1'],
        x: 120,
        y: 120,
      },
      {
        id: 'dyn-root-2',
        label: project.utility_shift_status === 'Critical Delay' ? 'Utility Shifting Bottleneck' : 'Contractor Liquidity / Supply Drag',
        category: 'Root Cause',
        type: 'ROOT_CAUSE',
        severity: project.utility_shift_status === 'Critical Delay' ? 'CRITICAL' : 'HIGH',
        currentValue: project.utility_shift_status,
        expectedValue: 'Clearances Complete',
        variance: 'Overdue Clearances',
        impactPoints: 10,
        evidence: `Clearance status recorded as "${project.utility_shift_status}".`,
        explanation: 'Inter-agency dependency halting critical path subgrade operations.',
        timeDelayEffect: 'Secondary schedule drag.',
        costEscalationEffect: 'Idle plant costs.',
        mitigation: 'Escalate to State Level Monitoring Committee for single-window resolution.',
        downstreamEffects: ['dyn-inter-1', 'dyn-inter-2'],
        x: 120,
        y: 380,
      },
      {
        id: 'dyn-inter-1',
        label: 'Execution Velocity & Milestone Lag',
        category: 'Intermediate Effect',
        type: 'INTERMEDIATE_EFFECT',
        severity: isCritical ? 'CRITICAL' : 'HIGH',
        currentValue: `${project.physical_progress}% Physical`,
        expectedValue: `${project.planned_progress}% Planned`,
        variance: `-${Math.max(0, project.planned_progress - project.physical_progress)}% Gap`,
        impactPoints: 14,
        evidence: `${project.milestones_delayed} of ${project.milestones_total} intermediate deliverables delayed.`,
        explanation: 'Reduced daily execution rates pushing key engineering milestones past baseline.',
        timeDelayEffect: `Accumulates +${project.predicted_delay_months} months critical path drag.`,
        costEscalationEffect: 'Consultancy and supervisory overhead expansion.',
        mitigation: 'Implement critical path crashing with parallel shifts.',
        downstreamEffects: ['dyn-down-1'],
        x: 450,
        y: 200,
      },
      {
        id: 'dyn-inter-2',
        label: 'Resource Idling & Cash Flow Variance',
        category: 'Intermediate Effect',
        type: 'INTERMEDIATE_EFFECT',
        severity: isHigh ? 'HIGH' : 'MEDIUM',
        currentValue: `${project.financial_progress}% Expended`,
        expectedValue: `${project.planned_progress}% Scheduled`,
        variance: `-${Math.max(0, project.planned_progress - project.financial_progress)}% Lag`,
        impactPoints: 8,
        evidence: `Financial expenditure trailing scheduled disbursement schedule.`,
        explanation: 'Reduced contractor liquidity leading to suboptimal on-site workforce deployment.',
        timeDelayEffect: 'Seasonal execution window loss.',
        costEscalationEffect: 'Variation bill interest accumulation.',
        mitigation: 'Expedite verified contractor payment milestones.',
        downstreamEffects: ['dyn-down-1'],
        x: 450,
        y: 420,
      },
      {
        id: 'dyn-down-1',
        label: 'Commercial COD Schedule Extension',
        category: 'Downstream Consequence',
        type: 'DOWNSTREAM_CONSEQUENCE',
        severity: isCritical ? 'CRITICAL' : 'HIGH',
        currentValue: `+${project.predicted_delay_months} Mo Delay`,
        expectedValue: 'On-Time COD',
        variance: `+${project.predicted_delay_months} Months`,
        impactPoints: 15,
        evidence: `Forecast completion shifted from ${project.original_completion_date} to ${project.current_completion_forecast}.`,
        explanation: 'Overall statutory commissioning milestone extended past baseline.',
        timeDelayEffect: `+${project.predicted_delay_months} months total project duration.`,
        costEscalationEffect: 'Interest During Construction (IDC) compounding.',
        mitigation: 'Prepare rapid commissioning protocol upon site handover.',
        downstreamEffects: ['dyn-term-1'],
        x: 750,
        y: 300,
      },
      {
        id: 'dyn-term-1',
        label: 'Terminal Budgetary Cost Escalation',
        category: 'Terminal Impact',
        type: 'TERMINAL_IMPACT',
        severity: isCritical ? 'CRITICAL' : 'HIGH',
        currentValue: `₹${project.revised_cost} Cr (+₹${project.predicted_cost_overrun} Cr)`,
        expectedValue: `₹${project.original_cost} Cr Original`,
        variance: `+₹${project.predicted_cost_overrun} Cr Exposure`,
        impactPoints: 18,
        evidence: `Predicted cost escalation with ${project.cost_overrun_probability}% probability.`,
        explanation: 'Terminal budgetary overrun driven by compounding delay costs and price indexation.',
        timeDelayEffect: 'Terminal outcome',
        costEscalationEffect: `₹${project.predicted_cost_overrun} Cr total exposure.`,
        mitigation: 'Submit Revised Cost Estimate to Ministry expenditure finance committee.',
        downstreamEffects: [],
        x: 1020,
        y: 300,
      },
    ];

    const edges: RiskEdge[] = [
      { id: 'de1', source: 'dyn-root-1', target: 'dyn-inter-1', label: 'Impairs Civil Pace' },
      { id: 'de2', source: 'dyn-root-2', target: 'dyn-inter-1', label: 'Clearance Stoppage' },
      { id: 'de3', source: 'dyn-root-2', target: 'dyn-inter-2', label: 'Billing Friction' },
      { id: 'de4', source: 'dyn-inter-1', target: 'dyn-down-1', label: 'Extends Milestones' },
      { id: 'de5', source: 'dyn-inter-2', target: 'dyn-down-1', label: 'Overhead Drag' },
      { id: 'de6', source: 'dyn-down-1', target: 'dyn-term-1', label: 'IDC & Escalation' },
    ];

    return {
      projectId: project.project_id,
      projectName: project.project_name,
      rootCausesCount: 2,
      downstreamRisksCount: 3,
      estimatedCostExposureCr: project.predicted_cost_overrun,
      estimatedDelayMonths: project.predicted_delay_months,
      summaryNarrative: `Operational risk concentration demonstrates how ${project.land_progress < project.land_target ? 'Right-of-Way deficits' : 'clearance bottlenecks'} propagate into ${project.milestones_delayed} delayed milestones, driving an estimated +${project.predicted_delay_months} months slippage and ₹${project.predicted_cost_overrun} Cr financial exposure.`,
      nodes,
      edges,
    };
  }
}

export const riskNetworkService = new RiskNetworkService();
