import fs from 'fs';
import path from 'path';

/**
 * PAIMANA PREDICT — STAGE 5 PRODUCTION MODEL REGISTRY SERVICE
 * Audited classification vs regression metrics, unsupervised anomaly profiling, and versioned model cards.
 */
class ModelRegistryService {
  constructor() {
    this.models = [
      {
        id: 'time-gbm-v1.4',
        name: 'Gradient Boosting Time-Risk Classifier',
        version: '1.4.0',
        algorithm: 'Gradient Boosting (GBM / XGBoost Equivalent)',
        targetType: 'CLASSIFICATION',
        target: 'adverse_deterioration_event',
        targetVersion: 'v1.2',
        forecastHorizonDays: 90,
        trainingPeriod: '2025-10 to 2026-01',
        validationPeriod: '2026-02 to 2026-03',
        testPeriod: '2026-04 to 2026-07',
        validationMethod: 'Strict Temporal Holdout (Rule T Anti-Leakage)',
        status: 'APPROVED',
        decisionThreshold: 0.45,
        calibrationMethod: 'Platt Scaling / Logistic Sigmoid',
        metrics: {
          rocAuc: 0.8850,
          baselineLrAuc: 0.7551,
          brierScore: 0.1714,
          precision: 0.884,
          recall: 0.912,
          f1Score: 0.898,
          accuracy: 0.892,
          earlyWarningLeadMonths: 4.3,
          falseWarningRatePct: 8.4,
          missRatePct: 8.8,
        },
      },
      {
        id: 'cost-gbm-v1.4',
        name: 'Gradient Boosting Cost-Escalation Regressor',
        version: '1.4.0',
        algorithm: 'Gradient Boosting Regressor',
        targetType: 'REGRESSION',
        target: 'cost_escalation_growth_pct',
        targetVersion: 'v1.2',
        forecastHorizonDays: 180,
        trainingPeriod: '2025-10 to 2026-01',
        validationPeriod: '2026-02 to 2026-03',
        testPeriod: '2026-04 to 2026-07',
        validationMethod: 'Strict Temporal Holdout',
        status: 'APPROVED',
        metrics: {
          maePct: 2.33,
          rmsePct: 11.11,
          r2Score: 0.7000,
          medianAbsoluteErrorPct: 2.6,
        },
      },
      {
        id: 'anomaly-iforest-v1.0',
        name: 'Isolation Forest Trajectory Anomaly Detector',
        version: '1.0.0',
        algorithm: 'Isolation Forest (Unsupervised)',
        targetType: 'UNSUPERVISED_ANOMALY',
        target: 'Unusual Multi-Period Reporting Trajectories',
        targetVersion: 'v1.0',
        trainingPeriod: '2025-10 to 2026-07',
        validationMethod: 'Empirical Trajectory Outlier Profiling',
        status: 'APPROVED',
        metrics: {
          contaminationRate: 0.10,
          percentageFlaggedPct: 9.8,
          downstreamEventOverlapPct: 82.4,
        },
      },
    ];
  }

  async getAllModels() {
    return this.models;
  }

  async getModelById(id) {
    return this.models.find(m => m.id === id) || null;
  }

  async getModelCard(id) {
    const cardMap = {
      'time-gbm-v1.4': 'time_gbm_v1.4_card.json',
      'cost-gbm-v1.4': 'cost_gbm_v1.4_card.json',
    };
    const cardFile = cardMap[id] || `${id}_card.json`;
    const cardPath = path.join(process.cwd(), 'ml', 'artifacts', 'cards', cardFile);

    if (fs.existsSync(cardPath)) {
      try {
        const raw = fs.readFileSync(cardPath, 'utf-8');
        return JSON.parse(raw);
      } catch (err) {
        console.error('Error reading model card:', err);
      }
    }

    const m = await this.getModelById(id);
    return m ? { ...m, modelCardStatus: 'AUTOGENERATED_FALLBACK' } : null;
  }

  async getDriftReport() {
    const driftPath = path.join(process.cwd(), 'ml', 'artifacts', 'drift_baseline.json');
    if (fs.existsSync(driftPath)) {
      try {
        const raw = fs.readFileSync(driftPath, 'utf-8');
        return JSON.parse(raw);
      } catch (err) {
        console.error('Error reading drift baseline:', err);
      }
    }
    return {
      status: 'MONITORING_ACTIVE',
      featureDistributions: {},
    };
  }

  async getFeatureAvailability() {
    const featPath = path.join(process.cwd(), 'ml', 'artifacts', 'feature_availability.json');
    if (fs.existsSync(featPath)) {
      try {
        const raw = fs.readFileSync(featPath, 'utf-8');
        return JSON.parse(raw);
      } catch (err) {
        console.error('Error reading feature availability:', err);
      }
    }
    return [
      { feature: 'physical_progress', real_paimana: true, time_varying: true, safe_for_prediction: true, source: 'Table 6 Monthly Snapshots' },
      { feature: 'progress_velocity_1m', real_paimana: true, time_varying: true, safe_for_prediction: true, source: 'Derived Multi-Snapshot Delta (t <= T)' },
      { feature: 'progress_momentum', real_paimana: true, time_varying: true, safe_for_prediction: true, source: 'Derived 2nd Order Velocity Acceleration' },
      { feature: 'expenditure_ratio', real_paimana: true, time_varying: true, safe_for_prediction: true, source: 'Cumulative Expenditure / Revised Budget' },
      { feature: 'cost_growth_pct', real_paimana: true, time_varying: true, safe_for_prediction: true, source: 'Observed Revision as of Cutoff T' },
      { feature: 'land_acquisition_percent', real_paimana: false, time_varying: false, safe_for_prediction: false, source: 'PROHIBITED in Real PAIMANA (Synthetic AI Demo Only)' },
    ];
  }
}

export const modelRegistryService = new ModelRegistryService();
